title: Blog
logo: /images/site-logo.png
locale: en-GB
email: jon@doveston.me.uk
description: We got both kinds, Dev and Ops!
baseurl: "/"
url: "https://jondoveston.github.io"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_analytics: UA-28013846-2
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: jondoveston
twitter_username: jondoveston
github_username:  jondoveston

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme"
feed:
  path: atom.xml
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

# Site Author
author: false
  # name: Jon Doveston
  # picture: /images/jondoveston.png
  # email: jon@doveston.me.uk
  # twitter: jondoveston
  # links:
  #   - title: Twitter
  #     url: https://twitter.com/jondoveston
  #     icon: fab fa-twitter-square
  #   - title: GitHub
  #     url: https://github.com/jondoveston
  #     icon: fab fa-github-square
  #   - title: Keybase
  #     url: https://keybase.io/jondoveston
  #     icon: fab fa-keybase

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/jondoveston
    icon: fab fa-twitter
  - title: GitHub
    url: https://github.com/jondoveston
    icon: fab fa-github
  - title: Keybase
    url: https://keybase.io/jondoveston
    icon: fab fa-keybase

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
